// try {
//     console.log(666);
// }
// catch (error) {

//     console.log(error)
// }
// finally {

//     console.log('finally Done')
// }




try {
    console.log('inside try');
    console.log(student);
}
catch (error) {
    console.log('inside Catch');


    console.log(error)
}
finally {

    console.log('finally Done')
}




